#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node" --no-warnings=DEP0040 "$basedir/node_modules/@google/gemini-cli/bundle/gemini.js" "$@"
else 
  exec node --no-warnings=DEP0040 "$basedir/node_modules/@google/gemini-cli/bundle/gemini.js" "$@"
fi
